#!/bin/sh
#
# hook script to format code and add missing license headers to every kotlin file.

echo "***** Run code formatting ******"
git stash -q --keep-index

./gradlew spotlessApply

status=$?

git stash pop -q

echo "***** Done with code formatting ******"

exit $status
